name: Test basic pipeline

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'

  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        required: true
        description: "Deployment Environment"
        options: 
        - Quality
      GitBranch:
        type: choice
        required: true
        description: "Git Branch"
        options: 
        - develop
      DeployToXMCloud:
        description: "Deploy to XM Cloud"
        type: boolean
        default: true
        required: true
env:
    Environment: ${{ inputs.Environment }}
    
jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      Environment: Dev

  Echo:
    name: Basic echo 
    runs-on: ubuntu-latest
    needs : [ test ]
    if: |
            always() && false &&
            ( ( github.event_name == 'push') && (needs.test.result == 'success' || needs.test.result == 'skipped' ) || 
            (  ( github.event_name == 'workflow_dispatch') && (github.event.inputs.DeployToXMCloud == 'true') &&
            (needs.test.result == 'success' || needs.test.result == 'skipped' )) )
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GitBranch }}
          fetch-depth: 0

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: "Get Current Date"
        id: today
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Use Date Output
        run: echo "The current date is ${{ steps.today.outputs.date }}"
