name: deploy
# **What it does**: On git push to release branch, it deploys release branch code to QA environment both for Sitecore CMS and Vercel.
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Echo:
    name: Basic echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GitBranch }}
          fetch-depth: 0

      - name: "Get Current Date"
        id: today
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Use Date Output
        run: echo "The current date is ${{ steps.today.outputs.date }}"

      - name: Define Paths Array
        id: define_paths
        run: |
          echo "cmspaths=src/items;src/platform;src/*.json" >> $GITHUB_ENV
          echo "firstalertpaths=src/projects" >> $GITHUB_ENV
          echo "prostorepath=src/prostore" >> $GITHUB_ENV

      - name: Check Modified Files
        id: check_files_cms
        run: |
          echo "=============== list modified files ==============="

          git diff --name-only HEAD^ HEAD > files.txt
          Deploytoxmcloud='false'
          DeploytoFirstalert='false'
          DeploytoProstore='false'

          while IFS= read -r file
          do
            echo "$file"
          done < files.txt

          echo "========XMCLOUD file check=========="
          
          while IFS= read -r file
          do
            IFS=';' read -r -a cmspaths_array <<< "$cmspaths"
            for path in "${cmspaths_array[@]}"; do
              if [[ "$file" == $path/* || "$file" == $path  ]]; then
                Deploytoxmcloud='true'
                break
              fi
            done
          done < files.txt
          echo "Deploytoxmcloud=$Deploytoxmcloud" >> $GITHUB_ENV

          echo "========FirstAlert file check=========="

          while IFS= read -r file
          do
            IFS=';' read -r -a firstalertpaths_array <<< "$firstalertpaths"
            for path in "${firstalertpaths_array[@]}"; do
              if [[ "$file" == $path/* || "$file" == $path ]]; then
                DeploytoFirstalert='true'
                break
              fi
            done
          done < files.txt
          echo "DeploytoFirstalert=$DeploytoFirstalert" >> $GITHUB_ENV

          echo "========Prostore file check=========="

          while IFS= read -r file
          do
            IFS=';' read -r -a firstalertpaths_array <<< "$prostorepath"
            for path in "${firstalertpaths_array[@]}"; do
              if [[ "$file" == $path/* || "$file" == $path ]]; then
                DeploytoProstore='true'
                break
              fi
            done
          done < files.txt
          echo "DeploytoProstore=$DeploytoProstore" >> $GITHUB_ENV

      - name: Output Deployment Decision
        run: |
          echo "Deploytoxmcloud = ${{ env.Deploytoxmcloud }}"
          echo "DeploytoFirstalert = ${{ env.DeploytoFirstalert }}"
          echo "DeploytoProstore = ${{ env.DeploytoProstore }}"
